### ISSUE TITLE
rofi coloring problem

### ISSUE THREAD

**Issue by HarshalRathore** [CodeHeister/dotfiles#2]
First Thanks for the awesome rice.

When I use your rofi powermenu direct from your repo with below command
`rofi -modi 'Powermenu:~/harshal/just_messing_around/dotfiles/.config/i3/powermenu.sh' -theme ~/harshal/just_messing_around/dotfiles/.config/rofi/powermenu.rasi -show Powermenu -icon-theme "Papirus"`

![2022-01-04-215720_1366x768_scrot](https://user-images.githubusercontent.com/76205196/148091244-62abad7b-6c93-46b2-a2e4-d74e4d2a98f1.png)

But with this command I get
`rofi -modi 'Powermenu:~/.config/rofi/powermenu/powermenu.sh' -theme ~/.config/rofi/powermenu/powermenu.rasi -show Powermenu -icon-theme "Papirus"`
![2022-01-04-220026_1366x768_scrot](https://user-images.githubusercontent.com/76205196/148091564-9be8c7c2-d633-4542-89cb-1a0965604fc2.png)

I want it like in the first image same as your screenshots, I can't even see what is being selected in white because of no shade.
I don't understand how and why this is happening both the files are the same only their location has changed.

**Comment by CodeHeister** [comment]
Picom blurs the background and the transparent colors are stored in `.config/rofi/colors.rasi`. To add blur, configure it through picom or find blur section in my picom configs. 
If you want to make it less transparent and include my colors, you should just copy `colors.rasi` directly to your rofi configs in the same directory or rewrite the path in rofi file. 

To add colors :
1. Copy `.config/rofi/colors.rasi` to your rofi configs.
2. To make the background less transparent, find `win-bg` in `colors.rasi`, change or delete **last 2 characters**.

As an example :
- `win-bg : #282c34cc;`

- `win-bg : #282c3411;`
to make it more transparent i set a lower number for alpha (last 2 characters)
- `win-bg : #282c34;`
to make the color solid i remove alpha

You may edit all colors in the same way.

To make easily a screenshot with a rofi without any external software you may use `rofi -no-lazy-grab -show drun -theme "~/.config/rofi/searcher.rasi"; maim --hidecursor | xclip -selection clipboard -t image/png` that uses maim and xclip or `rofi -no-lazy-grab -show drun -theme "~/.config/rofi/searcher.rasi"; maim --hidecursor | tee ~/Pictures/Screenshots/$(date "+Screenshot-%G-%m-%d_%H.%M.%S").png | xclip -selection clipboard -t image/png` that also uses tee to save screenshot in a file.

**Comment by HarshalRathore** [comment]
thank you a lot it is solved..

**Comment by HarshalRathore** [comment]
I have a one other problem please look at this [post](https://www.reddit.com/r/i3wm/comments/rw0vk0/i3lock_failing_in_rofi_powermenu/) it is related to your dotfies

**Comment by HarshalRathore** [comment]
@CodeHeister did you have the same problem with i3lock while using rofi powermenu. If so how did you solve it?

**Comment by CodeHeister** [comment]
I don't use system lock. I just suspend my system, logout or swap to another tty, but i have passwords everywhere so i don't have to worry about my system. Also nobody knows how to navigate in my system, so i'm calm. 
- `bindsym $mod+Shift+p exec i3lock -c 000000`  worked. 
- `xss-lock -- i3lock -n -c 000000` in `.xinitrc` and `loginctl lock-session` in rofi also worked.

Both options worked for me, so there should be no troubles.

**Comment by HarshalRathore** [comment]
Thanks for the info 👍!
I looked at rofi's .rsai file and scripts and they look likes just CSS to me, is that right? If so could you guide me to some resources for rofi component creation with CSS and .sh scripts for them I happen to be learning Frontend right now so maybe I'll try practising my skills there.
Thank you

**Comment by CodeHeister** [comment]
You can start with [this](https://github.com/davatorium/rofi/blob/next/doc/rofi-theme.5.markdown) or [this](https://manpages.debian.org/testing/rofi/rofi.1.en.html). There's everything described. Look for configs of your interest and try to configure on your own.
