### ISSUE TITLE
Eww glyphs not working

### ISSUE THREAD

**Issue by armoredvortex** [CodeHeister/dotfiles#5]
Maybe this is really a dumb issue and i'm missing something completely obvious.
I do have Both the Fonts installed (Iosevka, Hack Nerd Fonts) but the eww glyphs are not visible.

![image](https://user-images.githubusercontent.com/66690593/159015315-0cf78aec-f52b-4386-bb1c-fdb7e2f49edf.png)

Is there some other font which I have to install aswell. Please let me know :rocket:

**Comment by CodeHeister** [comment]
Thanks for the issue! 

Unfortunately, i forgot to add [Feather font](https://github.com/CodeHeister/dotfiles/blob/master/fonts/feather.ttf) for eww. Add it and it should work.

**Comment by armoredvortex** [comment]
Oh cool, my fault I didn't check the fonts folder in the repo. 🚀 

Edit: woops just realised you added it now.
Thanks for the awesome dotfiles though been daily driving the setup for a few days now

**Comment by CodeHeister** [comment]
My fault that i forgot this font 😅

I'm glad to hear that you enjoy it. Stay tuned for more changes, if i won't run out of ideas 😉

**Comment by OBLIXi-ON** [comment]
Hello! How to add fonts? I'm having the same issue. Actually I'm designing my own bar and I only have an yuck and an scss file under eww folder. Where should I add the fonts folder?

**Comment by CodeHeister** [comment]
### Arch wiki resources :
- [Font paths for font files](https://wiki.archlinux.org/title/font_configuration#Fontconfig_configuration)
- [Manual installation and font cache refreshing](https://wiki.archlinux.org/title/Fonts#Manual_installation)
